name: ci
on :
    pull_request:
        branches: [main]
concurrency:
    group: ${{ github.workflow }}-${{github.event.pull_request.number}}
jobs:
    run-test:
        uses: ./expression.yaml
        secrets: inherit