name: Docker
on: [workflow_dispatch]

jobs:
    docker-jaob:
        runs-on: ubuntu-latest
        container: 
            image: node:20.3-alpine3.17 
            ports:
                - 80

        steps:
            - name: Log node & OS version
              run: |
               node -v
               cat /etc/os-release
            - name: node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: 5+10
