name: logsvar
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      secretvar: ${{ secrets.boolean_secret }}
      #envvar: ${{ env.ENV_LEV_VAR}}
    steps:
      - name: to print the secret value
        run: echo "${{ env.secretvar }}"
     # - name: to print the env var
      #  run: echo "${{ env.envvar }}" 