name: matrix
on: 
    workflow_dispatch:
        inputs:
            os:
                description: Operating system
                default: "windows"
                type: string
            version:
                description: Versions
                default: "14,15,16"
                type: string

jobs:
    prepare-os-version:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{steps.matrix.outputs.result}}
        steps:
            - uses: actions/github-script@v6
              id: matrix
              with:
                script: "return { os:context.payload.inputs['os'].split(','), 'version':context.payload.inputs['version'].split(',') }"
                result: json
            - run: echo "${{steps.matrix.outputs.result}}"
            # - run: echo "${{outputs.}}"
    
    matrix-jobs:
        needs: prepare-os-version
        strategy:
            matrix:
                os: ${{ fromJson('needs.prepare-os-version.outputs.matrix').os}}
                version: ${{ fromJson('needs.prepare-os-version.outputs.matrix').version}}
        runs-on: ${{ matrix.os}}
        steps:
           - run: node -v
           - uses: actions/setup-node@v3
             with:
                version: ${{matrix.version}}
           - run: node -v

           

