name: Second Work folw 
on : 
    workflow_run:
        workflows: [First work flow]
        types: [completed]
jobs:
    echo-string:
      runs-on: ubuntu-latest
      steps:
        - run: echo "this is second workflowss"
    needjob:
      runs-on: ubuntu-latest
      needs:  echo-string
      steps:
        - run: echo "this is needed part" 